#!/bin/bash

declare -a user_inputs=("service_name" "user_name" "password")
declare -a input_errors=(
    'サービス名が入力されていません'
    'ユーザー名が入力されていません'
    'パスワードが入力されていません'
)
declare -a error_messages=()

echo 'パスワードマネージャーへようこそ！'
read -p 'サービス名を入力して下さい：' user_inputs[0]
read -p 'ユーザー名を入力して下さい：' user_inputs[1]
read -p 'パスワードを入力して下さい：' user_inputs[2]

# バリデーション処理：未入力の項目があればエラー文を配列に追加
# user_inputsのインデントをindentとしてループし、ユーザー入力情報とエラー文を紐づける
for indent in "${!user_inputs[@]}"; do
    if [ -z "${user_inputs[$indent]}" ]; then
        error_messages+=("${input_errors[$indent]}")
    fi
done
# 代入の確認テスト
echo "${error_messages[@]}"

# TODO:エラーの有無による条件分岐
echo "$service_name" : "$user_name" : "$password" >> user_inputs
echo -e "Thank you\033[31m!\033[0m"
