#!/bin/bash

declare -a user_inputs=("service_name" "user_name" "password")
declare -a input_errors=(
    'サービス名が入力されていません'
    'ユーザー名が入力されていません'
    'パスワードが入力されていません'
)
declare -a length_errors=(
    'サービス名は50文字以内で入力してください'
    'ユーザー名は50文字以内で入力してください'
    'パスワードは50文字以内で入力してください'
)
declare -a error_messages=()
MAX_CAHRACTERS=50

echo 'パスワードマネージャーへようこそ！'
read -p 'サービス名を入力して下さい：' user_inputs[0]
read -p 'ユーザー名を入力して下さい：' user_inputs[1]
read -p 'パスワードを入力して下さい：' user_inputs[2]

# バリデーション処理：未入力の項目があればエラー文を配列に追加
# user_inputsのインデントをindentとしてループし、ユーザー入力情報とエラー文を紐づける
for indent in "${!user_inputs[@]}"; do
    if [ -z "${user_inputs[$indent]}" ]; then
        error_messages+=("${input_errors[$indent]}")
    elif [ "${#user_inputs[$indent]}" -ge "$MAX_CAHRACTERS" ]; then
        error_messages+="${length_errors[$indent]}"
    fi
done

# エラーがある場合、配列のエラー文を出力
if [ -n "$error_messages" ]; then
    for error in "${error_messages[@]}"; do
        echo $error
    done
fi

# TODO:エラーが無い場合、ファイルにリダイレクトして、感謝文を出力
# echo "$service_name" : "$user_name" : "$password" >> user_inputs
# echo -e "Thank you\033[31m!\033[0m"
